language: java

sudo: required

services:
    - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login  -u $DOCKER_LOGIN -p $DOCKER_PASSWORD

    docker build --pull -t plantuml/plantuml-server:jetty -f Dockerfile.jetty . ;
    docker build --pull -t plantuml/plantuml-server:tomcat -f Dockerfile.tomcat . ;
    docker tag plantuml/plantuml-server:jetty plantuml/plantuml-server:latest ;

    docker push plantuml/plantuml-server:tomcat;
    docker push plantuml/plantuml-server:jetty;
    docker push plantuml/plantuml-server:latest;

    docker build --pull -t plantuml/plantuml-server:armv8a -f Dockerfile.armv8a . ;
    docker push plantuml/plantuml-server:armv8a;

    fi
